
# 统一判断一些编译器信息
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU" AND CMAKE_SYSTEM_NAME MATCHES "Windows")
set(COMPILE_NAME "MINGW")
else()
set(COMPILE_NAME "${CMAKE_CXX_COMPILER_ID}")
endif()

MESSAGE("TF_COMPILE_NAME: ${COMPILE_NAME}")
